name: "Open AI action code review"
description: "given a api key and prompt do a code review during the pull request and post a comment"
inputs:
  diff_from:
    default: "HEAD~1"
    description: "Commit SHA from where the diff is done"
    required: false
  diff_to:
    default: "HEAD"
    description: "Commit SHA from where the diff is done"
    required: false
  ghurl:
    default: "https://github.com"
    description: "github url"
    required: false
  current_sha:
    default: "none"
    description: "current sha"
    required: false
outputs:
  ai_comment:
    description: "Code review comment from AI"
runs:
  using: node16
  main: index.js
