name: "Open AI action code review"
description: "given a api key and prompt do a code review during the pull request and post a comment"
inputs:
  gh_token:
    default: "none"
    description: "github access token"
    required: false
  ghurl:
    default: "https://github.com"
    description: "github url"
    required: false
  diff_code:
    default: "code"
    description: "the code difference between two commits"
    required: false
  current_sha:
    default: "none"
    description: "current sha"
    required: false
outputs:
  openai_review:
    description: "Code review comment from AI"
runs:
  using: node16
  main: index.js
